(*Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.*)


// Create the sequence of Fibonacci Numbers
let fibSeq = Seq.unfold (fun (a,b) -> Some( a+b, (b, a+b) ) ) (0,1)

// take the first few numbers in the sequence and convert the sequence to a list
let answer = 
    fibSeq
    |> Seq.takeWhile (fun x -> x<=4000000 )
    |> Seq.filter (fun x-> x%2=0)
    |> Seq.sum
