(*Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.*)


let ispentagonal x = if x<1.0 then false else ((sqrt (24.0* x  + 1.0) + 1.0) / 6.0) % 1.0 = 0.0
let searchsequence = Seq.unfold (fun x-> Some(x*(2.0*x-1.0),x+1.0)) 144.0
let answer = searchsequence |> Seq.filter ispentagonal |> Seq.take 1 |> Seq.toList
